### ISSUE TITLE
Problem with WWW and non WWW

### ISSUE THREAD

**Issue by snzmnrdn** [Prajithp/letsencrypt-cpanel#44]
As i check and investigate, for non www working. with www not working. This is happen when you have alot of domain in 1 cpanel. Example

Primary domain - _abc.com_

**BUT** you install _def.com_ for ssl, so the Lets Encrypted registered your def.com as _def.abc.com_

so _www.def.com_ cannot be access. You only can access your SSL on _www.def.abc.com_

Im not sure this plugin working on subdomain or not

**Comment by itseasy21** [comment]
It happened with me also, the plugin took the internal subdomain rather then the main domain and then the www.subdomain.maindomain.com was not available so it threw error

**Comment by Prajithp** [comment]
Yes, it is because of when you create subdomain, cPanel will automatically add www.subdomain.maindomain.com and subdomain.maindomain.com to the system and when I make api calls, both will return as valid domain names. 

 Will add an option to select domains when you click on install certificate button, so that these types of issues can be avoided.
