### ISSUE TITLE
Genuine question

### ISSUE THREAD

**Issue by BeZazz** [Prajithp/letsencrypt-cpanel#90]
Is this project now dead?

Asking as I am wondering whether or not to remove this from servers.
NOTE: I do not want to but currently there is a few issues.

**Comment by WilliamIsted** [comment]
As I'm sure you're aware, the author of this project @Prajithp replied to an issue only 11 days ago, 9 days ago from the posting of this issue. I'd just like to point out that this type of "issue" doesn't particularly encourage authors to help assist with problems and in my opinion is one more reason as to why any author might feel like abandoning a project.

**Comment by Prajithp** [comment]
@BeZazz, I don't want to abandon this project as it is installed on 100+ servers and they are actively using it. The reason why I'm not active on this is, I got a new project from my office and therefore i have to work around 13 hours a day to complete it before the deadline. 

Could you please point out all issues you are facing? so that I can look into it when I get much free time.

**Comment by BeZazz** [comment]
Hi @Prajithp the main issue I have is
https://github.com/Prajithp/letsencrypt-cpanel/issues/87

I will go and donate $20 to you now as a thank you for the time you have put into this.

**Comment by BeZazz** [comment]
Sorry I tried but received the message.

> Currently PayPal accounts in India are only able to send payments. This recipient is not eligible to receive funds.

**Comment by Prajithp** [comment]
#87 would fix this issue
